name: Generate Snake Animation

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Generate Snake
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: AbhiMP2804
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Save generated files for later
        run: |
          mkdir snake_files
          cp dist/* snake_files/

      - name: Switch to output branch
        run: |
          git fetch origin output || true
          git checkout output 2>/dev/null || git checkout --orphan output
          git reset --hard
          git rm -rf .

      - name: Move files to output branch and push
        run: |
          cp snake_files/* .
          rm -rf snake_files dist

          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Update snake" || echo "No changes"
          git push origin output --force
