name: Generate Snake Animation

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Generate Snake
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: AbhiMP2804
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push snake to output branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git fetch origin output || true

          git checkout --orphan output
          git reset --hard

          mv dist/* .

          rm -rf dist

          git add .
          git commit -m "Update snake" || echo "No changes to commit"
          git push origin output --force
