name: Generate Snake Animation

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master

      - name: Generate Snake SVG
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: AbhiMP2804
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Store generated files
        run: |
          mkdir output_snk
          cp dist/* output_snk/

      - name: Switch to output branch
        run: |
          git fetch origin output || true
          if git show-ref --verify --quiet refs/heads/output; then
            git checkout output
          else
            git checkout --orphan output
          fi

          # Only remove files if they exist
          ls -A1 | xargs -I{} git rm -rf {} || true

      - name: Add and Commit snake files
        run: |
          cp output_snk/* .
          rm -rf output_snk dist

          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Update snake" || echo "No changes to commit"

      - name: Push to output branch
        run: |
          git push origin output --force
